name: laravel-starter
recipe: laravel
config:
  webroot: public
  database: postgres
  via: nginx
  cache: redis
  php: '8.4'
  composer_version: "2"
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

